# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.0.0-alpha.0
    hooks:
      - id: prettier
        exclude: ^app/$
  - repo: https://github.com/awebdeveloper/pre-commit-stylelint
    rev: 0.0.2
    hooks:
      - id: stylelint
        args: ["--fix"]
        additional_dependencies:
          [
            "stylelint@13.13.1",
            "stylelint-config-sass-guidelines@8.0.0",
            "stylelint-config-prettier@8.0.1",
          ]
        types_or: ["css", "scss"]
  - repo: local
    hooks:
      - id: stylish-haskell
        name: Check Haskell files with stylish-haskell
        entry: stack exec stylish-haskell -- -r -i
        language: system
        files: ^app/
        types: ["haskell"]
      - id: hlint
        name: Check Haskell files with HLint
        entry: stack exec hlint
        language: system
        files: ^app/
        types: ["haskell"]
exclude: |
  (?x)^(
      db/.*|
      doc/.*|
      graphs/.*|
      js/components/draw/.*|
      public/.*|
      vendor/.*|
      .*\.min\..*|
      \.stack-work/.*|
      \.yarn/.*|
      \.pnp\.js|
      .*/__snapshots__/.*|
  )$

ci:
  skip: [hlint, stylish-haskell]
