# Server Configuration Settings
port: 8000
logMessage: "Happstack.Server.AccessLog.Combined"

# Database Path
databasePath: "db/database.sqlite3"

# File Path Strings
graphPath: "./graphs/"
genCssPath: "./public/style/"

# URLs
timetableUrl: "https://ttb.utoronto.ca/"
timetableApiUrl: "https://api.easi.utoronto.ca/ttb/getPageableCourses"
fasCalendarUrl: "https://artsci.calendar.utoronto.ca/"
programsUrl: "https://artsci.calendar.utoronto.ca/listing-program-subject-areas"

# Term dates
fallStartDate: 2024-09-03
fallEndDate: 2024-12-03
winterStartDate: 2025-01-06
winterEndDate: 2025-04-04
outDay: 2026-01-01

# Holidays
holidaysList:
  - 20241014T
  - 20241028T
  - 20241029T
  - 20241030T
  - 20241031T
  - 20241101T
  - 20250217T
  - 20250218T
  - 20240219T
  - 20250220T
  - 20250221T
