# Server Configuration Settings
port: 8000
logMessage: "Happstack.Server.AccessLog.Combined"
logFile: "" # The file path to log server access to, e.g. "path/to/courseography.log"

# Database Path
databasePath: "db/database.sqlite3"

# File Path Strings
graphPath: "./graphs/"
genCssPath: "./public/style/"

# URLs
timetableUrl: "https://ttb.utoronto.ca/"
timetableApiUrl: "https://api.easi.utoronto.ca/ttb/getPageableCourses"
fasCalendarUrl: "https://artsci.calendar.utoronto.ca/"
programsUrl: "https://artsci.calendar.utoronto.ca/listing-program-subject-areas"

# Term dates
fallStartDate: 2026-09-08
fallEndDate: 2026-12-07
winterStartDate: 2027-01-11
winterEndDate: 2027-04-09
outDay: 2028-01-01

# Holidays
holidaysList:
  - 20261012T
  - 20261026T
  - 20261027T
  - 20261028T
  - 20261029T
  - 20261030T
  - 20270215T
  - 20270216T
  - 20270217T
  - 20270218T
  - 20270219T
  - 20270326T
