# Server Configuration Settings
port: 8000
logMessage: "Happstack.Server.AccessLog.Combined"
logFile: "" # The file path to log server access to, e.g. "path/to/courseography.log"

# Database Path
databasePath: "db/database.sqlite3"

# File Path Strings
graphPath: "./graphs/"
genCssPath: "./public/style/"

# URLs
timetableUrl: "https://ttb.utoronto.ca/"
timetableApiUrl: "https://api.easi.utoronto.ca/ttb/getPageableCourses"
fasCalendarUrl: "https://artsci.calendar.utoronto.ca/"
programsUrl: "https://artsci.calendar.utoronto.ca/listing-program-subject-areas"

# Term dates
fallStartDate: 2025-09-02
fallEndDate: 2025-12-02
winterStartDate: 2026-01-05
winterEndDate: 2026-04-02
outDay: 2027-01-01

# Holidays
holidaysList:
  - 20251013T
  - 20251027T
  - 20251028T
  - 20251029T
  - 20251030T
  - 20251130T
  - 20260216T
  - 20260217T
  - 20260218T
  - 20260219T
  - 20260220T
