nodeLinker: hoisted
allowBuilds:
  "@parcel/watcher": true
  core-js: true
  cypress: true
  unrs-resolver: true
overrides:
  pretty-format>react-is: "19.1.0"
peerDependencyRules:
  allowedVersions:
    eslint: "10"
    "@babel/core": "8"
