route = 
[ dir "grid" gridResponse,
  dir "graph" graphResponse,
  dir "image" graphImageResponse,
  dir "timetable-image" $ look "courses" >>= \x -> look "session" >>= timetableImageResponse x,
  dir "graph-fb" $ seeOther redirectUrlGraphEmail $ toResponse "",
  dir "post-fb" $ seeOther redirectUrlGraphPost $ toResponse "",
  dir "test" $ look "code" >>= getEmail,
  dir "test-post" $ look "code" >>= postToFacebook,
  dir "post" postResponse,
  dir "draw" drawResponse,                  
  dir "about" $ aboutResponse aboutContents,
  dir "privacy" $ privacyResponse privacyContents,
  dir "static" $ serveDirectory DisableBrowsing [] staticDir,
  dir "course" $ look "name" >>= retrieveCourse,
  dir "all-courses" $ liftIO allCourses,
  dir "graphs" $ liftIO queryGraphs,
  dir "course-info" $ look "dept" >>= courseInfo,
  dir "depts" $ liftIO deptList,
  dir "timesearch" searchResponse,
  dir "calendar" $ lookCookieValue "selected-lectures" >>= calendarResponse,
  dir "get-json-data" $ look "graphName" >>= \graphName -> liftIO $ getGraphJSON graphName,
  dir "loading" $ look "size" >>= loadingResponse,
  dir "save-json" $ look "jsonData" >>= \jsonStr -> look "nameData" >>= \nameStr -> liftIO $ saveGraphJSON jsonStr nameStr,
  notFoundResponse]
