flags:
  sendfile:
    portable: true
  regex-posix:
    _regex-posix-clib: true
extra-package-dbs: []
packages:
  - .
allow-newer: true
extra-deps:
  - stylish-haskell-0.14.6.0
compiler-check: newer-minor
resolver: lts-21.25
dump-logs: all
require-stack-version: ! ">= 1.6"
ghc-options:
  "$locals": -Wall -fwarn-tabs -Wno-incomplete-uni-patterns
