#!/bin/bash

python3 -c "
from urllib.request import urlopen
from html.parser import HTMLParser
import re

# Extract data from Time Table
html = urlopen('http://www.artsandscience.utoronto.ca/ofr/timetable/winter/csc.html')
htmlData = html.read()

# The regular expressions for all 6 fields
course = re.compile('^CSC\d{3}H1$')
section = re.compile('^[FS]{1}$')
lecture = re.compile('^[LT](0|2|1|5){1}[0152]{1}0{1}')
time = re.compile('^[MWTRF]{1,3}\d?[-]?\d?$|Cancel|TBA')
instructor = re.compile('^\w\.|Tba|Staff')
location = re.compile('^\w{2} \d{1,4}')



# Different cases for extracted data
class MyHTMLParser(HTMLParser):
    courseMemory = ''
    sectionMemory = ''
    typeMemory = ''
    timeMemory = ''
    locationMemory = ''


    def handle_data(self, data):
    	if course.match(data):
	        print('<tr><td>', data, '</td>\n')
	        self.courseMemory = data
    	elif section.match(data):
	        self.sectionMemory = data
    	elif lecture.match(data):
	        self.typeMemory = data
    	elif time.match(data):
	        self.timeMemory = data
    	elif location.match(data):
	        self.locationMemory = data
    	elif instructor.match(data):
	        print('<tr><td>',self.courseMemory,'</td><td>'+self.sectionMemory+'</td><td>' + self.typeMemory +'</td><td>' + self.timeMemory+ '</td><td>'+self.locationMemory+'</td><td>'+data+'</td>')

parser = MyHTMLParser(strict=False)

print('<table class=\"timeTable\">')
print('<tr>'
	+ '<td>Course</td>'
	+ '<td>Section</td>'
	+ '<td>Type</td>'
	+ '<td>Time</td>'
	+ '<td>Location</td>'
	+ '<td>Instructor</td>'
	+ '</tr><div><p>')
parser.feed(str(htmlData))
print('</p></div></table>')
" > res/timeTable