facultyWebsites = {
	'Abdelrahman': 'http://www.eecg.toronto.edu/~tsa/',
  'Bacchus': 'http://www.cs.toronto.edu/~fbacchus/',
  'Baecker': 'http://ron.taglab.ca/',
  'Baumgartner': 'http://www.cs.toronto.edu/~gfb/',
  'Bonner': 'http://www.cs.toronto.edu/~bonner/',
  'Borodin': 'http://www.cs.toronto.edu/~bor/',
  'Boutilier': 'http://www.cs.toronto.edu/~cebly/',
  'Brudno': 'http://www.cs.toronto.edu/~brudno/',
  'Campbell': 'http://www.cs.toronto.edu/~campbell/',
  'Chechik': 'http://www.cs.toronto.edu/~chechik/',
  'Christara': 'http://www.cs.toronto.edu/~ccc/',
  'Cook': 'http://www.cs.toronto.edu/~sacook/',
  'Craig': 'http://www.cs.toronto.edu/~mcraig/',
  'de Lara': 'http://www.cs.toronto.edu/~delara/',
  'Demke Brown': 'http://www.cs.toronto.edu/~demke/',
  'Dickinson': 'http://www.cs.toronto.edu/~sven/',
  'Ellen': 'http://www.cs.toronto.edu/~faith/',
  'Engels': 'http://www.cs.toronto.edu/~sengels/',
  'Enright': 'http://www.cs.toronto.edu/~enright/',
  'Fairgrieve': 'http://www.cs.toronto.edu/~tff/',
  'Farzan': 'http://www.cs.toronto.edu/~azadeh/',
  'Fidler': 'http://www.cs.toronto.edu/~fidler/',
  'Fiume': 'http://www.cs.toronto.edu/~elf/',
  'Ganjali': 'http://www.cs.toronto.edu/~yganjali/',
  'Gries': 'http://www.cs.toronto.edu/~pgries/',
  'Heap': 'http://www.cs.toronto.edu/~heap/',
  'Hirst': 'http://www.cs.toronto.edu/~gh/',
  'Horton': 'http://www.cs.toronto.edu/~dianeh/',
  'Jackson': 'http://www.cs.toronto.edu/~krj/',
  'Jepson': 'http://www.cs.toronto.edu/~jepson/',
  'Kutulakos': 'http://www.cs.toronto.edu/~kyros/',
  'Liu': 'http://www.cs.toronto.edu/~liudavid/',
  'Marbach': 'http://www.cs.toronto.edu/~marbach/',
  'McIlraith': 'http://www.cs.toronto.edu/~sheila/',
  'Miller': 'http://www.cs.toronto.edu/~miller/',
  'Neal': 'http://www.cs.toronto.edu/~radford/',
  'Pitassi': 'http://www.cs.toronto.edu/~toni/',
  'Pitt': 'http://www.cs.toronto.edu/~fpitt/',
  'Rackoff': 'http://www.cs.toronto.edu/~rackoff/',
  'Reid': 'http://www.cs.toronto.edu/~reid/',
  'Schroeder': 'http://www.cs.toronto.edu/~bianca/',
  'Singh': 'http://www.cs.toronto.edu/~karan/',
  'Urtasun': 'http://www.cs.toronto.edu/~urtasun/',
  'Wortman': 'http://www.cs.toronto.edu/~dw/',
  'Zemel': 'http://www.cs.toronto.edu/~zemel/'
}